apiVersion: 1

providers:
  - name: 'm169-cls'
    folder: './dashboards'
    type: file
    disableDeletion: false
    updateIntervalSeconds: 10
    allowUiUpdates: false
    options:
      path: /etc/grafana/provisioning/dashboards/
      foldersFromFilesStructure: true
