global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['prometheus:9090']

  - job_name: 'cadvisor'
    scrape_interval: 5s
    metrics_path: 'metrics'
    static_configs:
    - targets: ['cadvisor:8080']

  - job_name: 'nodeexporter'
    scrape_interval: 5s
    static_configs:
    - targets: ['nodeexporter:9100']
